"""Aegis demo: Flask API + form login. Deliberately small — meant as a
target for scanner pipelines generated by Aegis."""
from __future__ import annotations

import os
import secrets

from flask import Flask, jsonify, redirect, render_template_string, request, session, url_for

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY") or secrets.token_hex(32)

USERS = {"demo@example.com": "demo1234"}

ITEMS = [
    {"id": 1, "name": "Widget", "price": 19.99},
    {"id": 2, "name": "Gadget", "price": 24.50},
    {"id": 3, "name": "Sprocket", "price": 8.75},
]

LOGIN_HTML = """
<!doctype html>
<title>Login</title>
<h1>Sign in</h1>
{% if error %}<p style="color:red">{{ error }}</p>{% endif %}
<form method="post" action="/login">
  <label>Email <input name="email" type="email" required></label><br>
  <label>Password <input name="password" type="password" required></label><br>
  <button type="submit">Sign in</button>
</form>
"""

DASH_HTML = """
<!doctype html>
<title>Dashboard</title>
<h1>Welcome, {{ email }}</h1>
<ul>{% for i in items %}<li>{{ i.name }} — ${{ i.price }}</li>{% endfor %}</ul>
<form method="post" action="/logout"><button>Sign out</button></form>
"""


@app.get("/")
def index():
    return "<h1>Aegis demo (Python)</h1><a href='/login'>Sign in</a>"


@app.get("/login")
def login_form():
    return render_template_string(LOGIN_HTML, error=None)


@app.post("/login")
def login_submit():
    email = request.form.get("email", "")
    password = request.form.get("password", "")
    if USERS.get(email) == password:
        session["email"] = email
        return redirect(url_for("dashboard"))
    return render_template_string(LOGIN_HTML, error="Invalid credentials"), 401


@app.get("/dashboard")
def dashboard():
    email = session.get("email")
    if not email:
        return redirect(url_for("login_form"))
    return render_template_string(DASH_HTML, email=email, items=ITEMS)


@app.post("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))


@app.get("/api/items")
def api_items():
    if not session.get("email"):
        return jsonify(error="unauthorized"), 401
    return jsonify(items=ITEMS)


@app.get("/healthz")
def healthz():
    return {"status": "ok"}


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", "5000")))
